//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Caisse.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Caisse.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan or enter CUP.
        /// </summary>
        public static string Caisse_CUP_Input_Watermark {
            get {
                return ResourceManager.GetString("Caisse_CUP_Input_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string Caisse_Finish_Transaction_Btn {
            get {
                return ResourceManager.GetString("Caisse_Finish_Transaction_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Caisse_Product_Name_Header {
            get {
                return ResourceManager.GetString("Caisse_Product_Name_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        public static string Caisse_Product_Price_Subtotal {
            get {
                return ResourceManager.GetString("Caisse_Product_Price_Subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        public static string Caisse_Subtotal_Title {
            get {
                return ResourceManager.GetString("Caisse_Subtotal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxes.
        /// </summary>
        public static string Caisse_Taxes_Title {
            get {
                return ResourceManager.GetString("Caisse_Taxes_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        public static string Caisse_Total_Title {
            get {
                return ResourceManager.GetString("Caisse_Total_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TPS (5.000%):.
        /// </summary>
        public static string Caisse_Tps_Details {
            get {
                return ResourceManager.GetString("Caisse_Tps_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TVQ (9.975%):.
        /// </summary>
        public static string Caisse_Tvq_Details {
            get {
                return ResourceManager.GetString("Caisse_Tvq_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Mode_Add {
            get {
                return ResourceManager.GetString("Mode_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple.
        /// </summary>
        public static string Mode_Many {
            get {
                return ResourceManager.GetString("Mode_Many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Mode_Remove {
            get {
                return ResourceManager.GetString("Mode_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        public static string Mode_Single {
            get {
                return ResourceManager.GetString("Mode_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modes.
        /// </summary>
        public static string Mode_Title {
            get {
                return ResourceManager.GetString("Mode_Title", resourceCulture);
            }
        }
    }
}
