//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SGI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer.
        /// </summary>
        public static string Add_CreateAndContinue_Btn {
            get {
                return ResourceManager.GetString("Add_CreateAndContinue_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer et quitter.
        /// </summary>
        public static string Add_CreateAndQuit_Btn {
            get {
                return ResourceManager.GetString("Add_CreateAndQuit_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixe ($).
        /// </summary>
        public static string Add_DiscountCombo_Fixed {
            get {
                return ResourceManager.GetString("Add_DiscountCombo_Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun.
        /// </summary>
        public static string Add_DiscountCombo_None {
            get {
                return ResourceManager.GetString("Add_DiscountCombo_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pourcentage (%).
        /// </summary>
        public static string Add_DiscountCombo_Percent {
            get {
                return ResourceManager.GetString("Add_DiscountCombo_Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Universel de Produit (CUP): .
        /// </summary>
        public static string Add_Labels_CUP {
            get {
                return ResourceManager.GetString("Add_Labels_CUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        public static string Add_Labels_DeptName {
            get {
                return ResourceManager.GetString("Add_Labels_DeptName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rabais.
        /// </summary>
        public static string Add_Labels_Discounts {
            get {
                return ResourceManager.GetString("Add_Labels_Discounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prix:.
        /// </summary>
        public static string Add_Labels_PriceInput {
            get {
                return ResourceManager.GetString("Add_Labels_PriceInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prix &amp; Qty.
        /// </summary>
        public static string Add_Labels_PriceQty {
            get {
                return ResourceManager.GetString("Add_Labels_PriceQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du produit:.
        /// </summary>
        public static string Add_Labels_ProductName {
            get {
                return ResourceManager.GetString("Add_Labels_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type d&apos;unité:.
        /// </summary>
        public static string Add_Labels_ProductUnit {
            get {
                return ResourceManager.GetString("Add_Labels_ProductUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty:.
        /// </summary>
        public static string Add_Labels_QtyInput {
            get {
                return ResourceManager.GetString("Add_Labels_QtyInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxes.
        /// </summary>
        public static string Add_Labels_Taxes {
            get {
                return ResourceManager.GetString("Add_Labels_Taxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendeur.
        /// </summary>
        public static string Add_Labels_VendorName {
            get {
                return ResourceManager.GetString("Add_Labels_VendorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retour à la liste.
        /// </summary>
        public static string Add_Previous_Btn {
            get {
                return ResourceManager.GetString("Add_Previous_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réinitialiser.
        /// </summary>
        public static string Add_Reset_Btn {
            get {
                return ResourceManager.GetString("Add_Reset_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter un nouveau produit.
        /// </summary>
        public static string Add_Title {
            get {
                return ResourceManager.GetString("Add_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infos du produit.
        /// </summary>
        public static string Add_Titles_ProductInfo {
            get {
                return ResourceManager.GetString("Add_Titles_ProductInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détails de vente.
        /// </summary>
        public static string Add_Titles_SalesInfo {
            get {
                return ResourceManager.GetString("Add_Titles_SalesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mettre à jour.
        /// </summary>
        public static string Add_UpdateAndContinue_Btn {
            get {
                return ResourceManager.GetString("Add_UpdateAndContinue_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mettre à jour et quitter.
        /// </summary>
        public static string Add_UpdateAndQuit_Btn {
            get {
                return ResourceManager.GetString("Add_UpdateAndQuit_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification d&apos;un produit existant....
        /// </summary>
        public static string Edit_Title {
            get {
                return ResourceManager.GetString("Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quitter.
        /// </summary>
        public static string List_Quit_App {
            get {
                return ResourceManager.GetString("List_Quit_App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapports.
        /// </summary>
        public static string List_Report_Btn {
            get {
                return ResourceManager.GetString("List_Report_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Système de gestion de produits Super CChic.
        /// </summary>
        public static string List_Title {
            get {
                return ResourceManager.GetString("List_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appliquer Tps.
        /// </summary>
        public static string Product_ApplyTps {
            get {
                return ResourceManager.GetString("Product_ApplyTps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appliquer Tvq.
        /// </summary>
        public static string Product_ApplyTvq {
            get {
                return ResourceManager.GetString("Product_ApplyTvq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companie.
        /// </summary>
        public static string Product_Company {
            get {
                return ResourceManager.GetString("Product_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUP.
        /// </summary>
        public static string Product_CUP {
            get {
                return ResourceManager.GetString("Product_CUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Département.
        /// </summary>
        public static string Product_Dept {
            get {
                return ResourceManager.GetString("Product_Dept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rabais.
        /// </summary>
        public static string Product_DiscountAmt {
            get {
                return ResourceManager.GetString("Product_DiscountAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de rabais.
        /// </summary>
        public static string Product_DiscountType {
            get {
                return ResourceManager.GetString("Product_DiscountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string Product_Name {
            get {
                return ResourceManager.GetString("Product_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prix.
        /// </summary>
        public static string Product_Price {
            get {
                return ResourceManager.GetString("Product_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string Product_Qty {
            get {
                return ResourceManager.GetString("Product_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unité.
        /// </summary>
        public static string Product_UnitType {
            get {
                return ResourceManager.GetString("Product_UnitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Générateur de rapports Super CCHic.
        /// </summary>
        public static string Reports_Title {
            get {
                return ResourceManager.GetString("Reports_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter.
        /// </summary>
        public static string Section_Action_Add {
            get {
                return ResourceManager.GetString("Section_Action_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer.
        /// </summary>
        public static string Section_Action_Delete {
            get {
                return ResourceManager.GetString("Section_Action_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier.
        /// </summary>
        public static string Section_Action_Edit {
            get {
                return ResourceManager.GetString("Section_Action_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Section_Action_Title {
            get {
                return ResourceManager.GetString("Section_Action_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez vous vraiment supprimer.
        /// </summary>
        public static string SGI_Delete_Msg {
            get {
                return ResourceManager.GetString("SGI_Delete_Msg", resourceCulture);
            }
        }
    }
}
