//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SGI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Add_CreateAndContinue_Btn {
            get {
                return ResourceManager.GetString("Add_CreateAndContinue_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create and quit.
        /// </summary>
        public static string Add_CreateAndQuit_Btn {
            get {
                return ResourceManager.GetString("Add_CreateAndQuit_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed ($).
        /// </summary>
        public static string Add_DiscountCombo_Fixed {
            get {
                return ResourceManager.GetString("Add_DiscountCombo_Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Add_DiscountCombo_None {
            get {
                return ResourceManager.GetString("Add_DiscountCombo_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent (%).
        /// </summary>
        public static string Add_DiscountCombo_Percent {
            get {
                return ResourceManager.GetString("Add_DiscountCombo_Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Universal Product Code (UPC):.
        /// </summary>
        public static string Add_Labels_CUP {
            get {
                return ResourceManager.GetString("Add_Labels_CUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        public static string Add_Labels_DeptName {
            get {
                return ResourceManager.GetString("Add_Labels_DeptName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string Add_Labels_Discounts {
            get {
                return ResourceManager.GetString("Add_Labels_Discounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price:.
        /// </summary>
        public static string Add_Labels_PriceInput {
            get {
                return ResourceManager.GetString("Add_Labels_PriceInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price &amp; Qty.
        /// </summary>
        public static string Add_Labels_PriceQty {
            get {
                return ResourceManager.GetString("Add_Labels_PriceQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name:.
        /// </summary>
        public static string Add_Labels_ProductName {
            get {
                return ResourceManager.GetString("Add_Labels_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity type:.
        /// </summary>
        public static string Add_Labels_ProductUnit {
            get {
                return ResourceManager.GetString("Add_Labels_ProductUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty:.
        /// </summary>
        public static string Add_Labels_QtyInput {
            get {
                return ResourceManager.GetString("Add_Labels_QtyInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxes.
        /// </summary>
        public static string Add_Labels_Taxes {
            get {
                return ResourceManager.GetString("Add_Labels_Taxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor.
        /// </summary>
        public static string Add_Labels_VendorName {
            get {
                return ResourceManager.GetString("Add_Labels_VendorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to list.
        /// </summary>
        public static string Add_Previous_Btn {
            get {
                return ResourceManager.GetString("Add_Previous_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Values.
        /// </summary>
        public static string Add_Reset_Btn {
            get {
                return ResourceManager.GetString("Add_Reset_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new product.
        /// </summary>
        public static string Add_Title {
            get {
                return ResourceManager.GetString("Add_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Info.
        /// </summary>
        public static string Add_Titles_ProductInfo {
            get {
                return ResourceManager.GetString("Add_Titles_ProductInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing.
        /// </summary>
        public static string Add_Titles_SalesInfo {
            get {
                return ResourceManager.GetString("Add_Titles_SalesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing an existing product....
        /// </summary>
        public static string Edit_Title {
            get {
                return ResourceManager.GetString("Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string List_Quit_App {
            get {
                return ResourceManager.GetString("List_Quit_App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuperCChic Product Management.
        /// </summary>
        public static string List_Title {
            get {
                return ResourceManager.GetString("List_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Section_Action_Add {
            get {
                return ResourceManager.GetString("Section_Action_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Section_Action_Delete {
            get {
                return ResourceManager.GetString("Section_Action_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Section_Action_Edit {
            get {
                return ResourceManager.GetString("Section_Action_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Section_Action_Title {
            get {
                return ResourceManager.GetString("Section_Action_Title", resourceCulture);
            }
        }
    }
}
